package shoot

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"time"
)

// RequestOption customizes a single outgoing HTTP request.
//
// A generated REST method may optionally accept ...RequestOption as its last
// parameter. Options are applied after configured and statically declared
// headers, so request-specific values take precedence.
type RequestOption interface {
	apply(*requestOptions) error
}

type requestOptions struct {
	request  *http.Request
	timeout  time.Duration
	deadline *time.Time
}

type requestOptionFunc func(*requestOptions) error

func (f requestOptionFunc) apply(options *requestOptions) error {
	return f(options)
}

// ApplyRequestOptions applies request options and returns a cleanup function.
// It is primarily intended for code generated by shoot. The cleanup function
// must be called after the response body has been consumed.
func ApplyRequestOptions(req *http.Request, defaultTimeout time.Duration, options ...RequestOption) (func(), error) {
	if req == nil {
		return func() {}, fmt.Errorf("request must not be nil")
	}
	config := &requestOptions{
		request: req,
		timeout: defaultTimeout,
	}
	for _, option := range options {
		if option == nil {
			continue
		}
		if err := option.apply(config); err != nil {
			return func() {}, err
		}
	}

	if config.deadline != nil {
		ctx, cancel := context.WithDeadline(req.Context(), *config.deadline)
		*req = *req.WithContext(ctx)
		return cancel, nil
	}
	if config.timeout > 0 {
		ctx, cancel := context.WithTimeout(req.Context(), config.timeout)
		*req = *req.WithContext(ctx)
		return cancel, nil
	}
	return func() {}, nil
}

// WithHeader sets a header on a single outgoing HTTP request.
func WithHeader(name, value string) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.request.Header.Set(name, value)
		return nil
	})
}

// WithHeaders sets headers on a single outgoing HTTP request. Header values
// replace existing values with the same name.
func WithHeaders(headers http.Header) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		for name, values := range headers {
			options.request.Header.Del(name)
			for _, value := range values {
				options.request.Header.Add(name, value)
			}
		}
		return nil
	})
}

// WithBearerToken sets the Authorization header using Bearer authentication.
func WithBearerToken(token string) RequestOption {
	return WithHeader("Authorization", "Bearer "+token)
}

// WithBasicAuth sets the Authorization header using HTTP Basic authentication.
func WithBasicAuth(username, password string) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.request.SetBasicAuth(username, password)
		return nil
	})
}

// WithAccept sets the Accept header.
func WithAccept(mediaType string) RequestOption {
	return WithHeader("Accept", mediaType)
}

// WithContentType sets the Content-Type header.
func WithContentType(mediaType string) RequestOption {
	return WithHeader("Content-Type", mediaType)
}

// WithUserAgent sets the User-Agent header.
func WithUserAgent(userAgent string) RequestOption {
	return WithHeader("User-Agent", userAgent)
}

// WithQueryParam sets one query parameter, replacing existing values for key.
func WithQueryParam(key, value string) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if options.request.URL == nil {
			return fmt.Errorf("request URL must not be nil")
		}
		query := options.request.URL.Query()
		query.Set(key, value)
		options.request.URL.RawQuery = query.Encode()
		return nil
	})
}

// WithQueryParams sets query parameters, replacing existing values for each
// supplied key while preserving multiple supplied values.
func WithQueryParams(values url.Values) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if options.request.URL == nil {
			return fmt.Errorf("request URL must not be nil")
		}
		query := options.request.URL.Query()
		for key, items := range values {
			query.Del(key)
			for _, item := range items {
				query.Add(key, item)
			}
		}
		options.request.URL.RawQuery = query.Encode()
		return nil
	})
}

// WithCookie adds a cookie to a single outgoing HTTP request.
func WithCookie(cookie *http.Cookie) RequestOption {
	return WithCookies(cookie)
}

// WithCookies adds cookies to a single outgoing HTTP request.
func WithCookies(cookies ...*http.Cookie) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		for _, cookie := range cookies {
			if cookie == nil {
				return fmt.Errorf("cookie must not be nil")
			}
		}
		for _, cookie := range cookies {
			options.request.AddCookie(cookie)
		}
		return nil
	})
}

// WithTimeout overrides the client-level timeout for a single request. A
// non-positive duration disables the client-level timeout for that request.
func WithTimeout(timeout time.Duration) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.timeout = timeout
		options.deadline = nil
		return nil
	})
}

// WithDeadline overrides the client-level timeout with an absolute deadline for
// a single request.
func WithDeadline(deadline time.Time) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.deadline = &deadline
		return nil
	})
}

// WithRequestModifier applies a custom request mutation. Use it for request
// properties that do not have a dedicated option.
func WithRequestModifier(modifier func(*http.Request) error) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if modifier == nil {
			return fmt.Errorf("request modifier must not be nil")
		}
		return modifier(options.request)
	})
}
