package shoot

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"time"
)

// RequestOption customizes a single outgoing HTTP request.
//
// A generated REST method may optionally accept ...RequestOption as its last
// parameter. Options are applied after configured and statically declared
// headers, so request-specific values take precedence.
type RequestOption interface {
	apply(*requestOptions) error
}

type requestOptions struct {
	request            *http.Request
	timeout            time.Duration
	deadline           *time.Time
	retryCount         *int
	retryWait          *time.Duration
	retryMaxWait       *time.Duration
	allowNonIdempotent *bool
	disableDefaults    *bool
	retryStrategy      RetryDelayStrategy
	retryConditions    []RetryCondition
}

// Call is the resolved per-request policy produced by ApplyRequestOptions.
// Cancel releases the overall deadline. Per-attempt timeouts are applied by Do.
type Call struct {
	cancel             func()
	attemptTimeout     time.Duration
	retryCount         *int
	retryWait          *time.Duration
	retryMaxWait       *time.Duration
	allowNonIdempotent *bool
	disableDefaults    *bool
	retryStrategy      RetryDelayStrategy
	retryConditions    []RetryCondition
}

// Cancel releases the overall deadline set by WithDeadline.
func (c Call) Cancel() {
	if c.cancel != nil {
		c.cancel()
	}
}

type requestOptionFunc func(*requestOptions) error

func (f requestOptionFunc) apply(options *requestOptions) error {
	return f(options)
}

// ApplyRequestOptions applies request options and returns the call policy.
// It is primarily intended for code generated by shoot. Cancel must be called
// after the response body has been consumed. A positive timeout is recorded
// for each attempt and is not attached to the request context here; a deadline
// is attached immediately and bounds the whole call, including retries.
func ApplyRequestOptions(req *http.Request, defaultTimeout time.Duration, options ...RequestOption) (Call, error) {
	if req == nil {
		return Call{}, fmt.Errorf("request must not be nil")
	}
	config := &requestOptions{
		request: req,
		timeout: defaultTimeout,
	}
	for _, option := range options {
		if option == nil {
			continue
		}
		if err := option.apply(config); err != nil {
			return Call{}, err
		}
	}

	call := Call{
		attemptTimeout:     config.timeout,
		retryCount:         config.retryCount,
		retryWait:          config.retryWait,
		retryMaxWait:       config.retryMaxWait,
		allowNonIdempotent: config.allowNonIdempotent,
		disableDefaults:    config.disableDefaults,
		retryStrategy:      config.retryStrategy,
		retryConditions:    config.retryConditions,
	}
	if config.deadline != nil {
		ctx, cancel := context.WithDeadline(req.Context(), *config.deadline)
		*req = *req.WithContext(ctx)
		call.cancel = cancel
	}
	return call, nil
}

// WithHeader sets a header on a single outgoing HTTP request.
func WithHeader(name, value string) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.request.Header.Set(name, value)
		return nil
	})
}

// WithHeaders sets headers on a single outgoing HTTP request. Header values
// replace existing values with the same name.
func WithHeaders(headers http.Header) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		for name, values := range headers {
			options.request.Header.Del(name)
			for _, value := range values {
				options.request.Header.Add(name, value)
			}
		}
		return nil
	})
}

// WithBearerToken sets the Authorization header using Bearer authentication.
func WithBearerToken(token string) RequestOption {
	return WithHeader("Authorization", "Bearer "+token)
}

// WithBasicAuth sets the Authorization header using HTTP Basic authentication.
func WithBasicAuth(username, password string) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.request.SetBasicAuth(username, password)
		return nil
	})
}

// WithAccept sets the Accept header.
func WithAccept(mediaType string) RequestOption {
	return WithHeader("Accept", mediaType)
}

// WithContentType sets the Content-Type header.
func WithContentType(mediaType string) RequestOption {
	return WithHeader("Content-Type", mediaType)
}

// WithUserAgent sets the User-Agent header.
func WithUserAgent(userAgent string) RequestOption {
	return WithHeader("User-Agent", userAgent)
}

// WithQueryParam sets one query parameter, replacing existing values for key.
func WithQueryParam(key, value string) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if options.request.URL == nil {
			return fmt.Errorf("request URL must not be nil")
		}
		query := options.request.URL.Query()
		query.Set(key, value)
		options.request.URL.RawQuery = query.Encode()
		return nil
	})
}

// WithQueryParams sets query parameters, replacing existing values for each
// supplied key while preserving multiple supplied values.
func WithQueryParams(values url.Values) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if options.request.URL == nil {
			return fmt.Errorf("request URL must not be nil")
		}
		query := options.request.URL.Query()
		for key, items := range values {
			query.Del(key)
			for _, item := range items {
				query.Add(key, item)
			}
		}
		options.request.URL.RawQuery = query.Encode()
		return nil
	})
}

// WithCookie adds a cookie to a single outgoing HTTP request.
func WithCookie(cookie *http.Cookie) RequestOption {
	return WithCookies(cookie)
}

// WithCookies adds cookies to a single outgoing HTTP request.
func WithCookies(cookies ...*http.Cookie) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		for _, cookie := range cookies {
			if cookie == nil {
				return fmt.Errorf("cookie must not be nil")
			}
		}
		for _, cookie := range cookies {
			options.request.AddCookie(cookie)
		}
		return nil
	})
}

// WithTimeout sets the per-attempt timeout for a single request. Each retry
// receives a fresh timeout derived from the parent context, so it cannot
// extend the caller's context or a WithDeadline budget. A non-positive
// duration disables the client-level per-attempt timeout for that request.
func WithTimeout(timeout time.Duration) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.timeout = timeout
		options.deadline = nil
		return nil
	})
}

// WithDeadline sets an absolute deadline for the whole call, including retries
// and the waits between them. A per-attempt timeout still applies inside the
// time that remains.
func WithDeadline(deadline time.Time) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.deadline = &deadline
		return nil
	})
}

// WithRetryCount overrides the number of additional attempts for one request.
func WithRetryCount(count int) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.retryCount = &count
		return nil
	})
}

// WithRetryWait overrides the backoff window for one request.
// wait is the base delay and max is the cap used by the default strategy.
func WithRetryWait(wait, max time.Duration) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		options.retryWait = &wait
		options.retryMaxWait = &max
		return nil
	})
}

// WithAllowNonIdempotentRetry allows POST and PATCH to be retried for one request.
func WithAllowNonIdempotentRetry() RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		allow := true
		options.allowNonIdempotent = &allow
		return nil
	})
}

// WithoutDefaultRetryConditions disables the built-in status and network
// conditions for one request. Conditions added explicitly still run.
func WithoutDefaultRetryConditions() RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		disable := true
		options.disableDefaults = &disable
		return nil
	})
}

// WithRetryCondition adds a retry condition for one request. Request
// conditions run after the defaults and before client-level conditions.
// The first condition that returns true selects a retry.
func WithRetryCondition(condition RetryCondition) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if condition == nil {
			return fmt.Errorf("retry condition must not be nil")
		}
		options.retryConditions = append(options.retryConditions, condition)
		return nil
	})
}

// WithRetryStrategy overrides the delay strategy for one request.
// A Retry-After header on 429 and 503 is still honored first.
func WithRetryStrategy(strategy RetryDelayStrategy) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if strategy == nil {
			return fmt.Errorf("retry strategy must not be nil")
		}
		options.retryStrategy = strategy
		return nil
	})
}

// WithRequestModifier applies a custom request mutation. Use it for request
// properties that do not have a dedicated option.
func WithRequestModifier(modifier func(*http.Request) error) RequestOption {
	return requestOptionFunc(func(options *requestOptions) error {
		if modifier == nil {
			return fmt.Errorf("request modifier must not be nil")
		}
		return modifier(options.request)
	})
}
