// Code generated by "shoot new -getset -opt -short -type=RestConf -ver=v0.0.0"; DO NOT EDIT. (v0.0.0)

package shoot

// NewRestConf constructs a new instance of type RestConf
func NewRestConf(baseUrl string, timeout string, enableLogging bool, defaultHeaders map[string]string, retry RetryConfig) *RestConf {
	return &RestConf{
		baseURL:        baseUrl,
		timeout:        timeout,
		enableLogging:  enableLogging,
		defaultHeaders: defaultHeaders,
		retry:          retry,
	}
}

// With initializes this instance using the functional options pattern
func (r *RestConf) With(opts ...Option[RestConf, *RestConf]) *RestConf {
	r.SetDefault()
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// BaseURL is a configuration for the filed baseURL
func BaseURL(baseURL_ string) Option[RestConf, *RestConf] {
	return func(r *RestConf) {
		r.baseURL = baseURL_
	}
}

// Timeout is a configuration for the filed timeout
func Timeout(timeout_ string) Option[RestConf, *RestConf] {
	return func(r *RestConf) {
		r.timeout = timeout_
	}
}

// EnableLogging is a configuration for the filed enableLogging
func EnableLogging(enableLogging_ bool) Option[RestConf, *RestConf] {
	return func(r *RestConf) {
		r.enableLogging = enableLogging_
	}
}

// DefaultHeaders is a configuration for the filed defaultHeaders
func DefaultHeaders(defaultHeaders_ map[string]string) Option[RestConf, *RestConf] {
	return func(r *RestConf) {
		r.defaultHeaders = defaultHeaders_
	}
}

// Retry is a configuration for the filed retry
func Retry(retry_ RetryConfig) Option[RestConf, *RestConf] {
	return func(r *RestConf) {
		r.retry = retry_
	}
}

// SetDefault sets the default values
func (r *RestConf) SetDefault() {
	r.timeout = "0s"
}

// BaseURL gets the value of field baseURL
func (r *RestConf) BaseURL() string {
	return r.baseURL
}

// Timeout gets the value of field timeout
func (r *RestConf) Timeout() string {
	return r.timeout
}

// EnableLogging gets the value of field enableLogging
func (r *RestConf) EnableLogging() bool {
	return r.enableLogging
}

// DefaultHeaders gets the value of field defaultHeaders
func (r *RestConf) DefaultHeaders() map[string]string {
	return r.defaultHeaders
}

// Retry gets the value of field retry
func (r *RestConf) Retry() RetryConfig {
	return r.retry
}

// SetBaseURL sets the value of field baseURL
func (r *RestConf) SetBaseURL(baseURL_ string) {
	r.baseURL = baseURL_
}

// SetTimeout sets the value of field timeout
func (r *RestConf) SetTimeout(timeout_ string) {
	r.timeout = timeout_
}

// SetEnableLogging sets the value of field enableLogging
func (r *RestConf) SetEnableLogging(enableLogging_ bool) {
	r.enableLogging = enableLogging_
}

// SetDefaultHeaders sets the value of field defaultHeaders
func (r *RestConf) SetDefaultHeaders(defaultHeaders_ map[string]string) {
	r.defaultHeaders = defaultHeaders_
}

// SetRetry sets the value of field retry
func (r *RestConf) SetRetry(retry_ RetryConfig) {
	r.retry = retry_
}

// RestConfGetter is read-only interface for RestConf type
type RestConfGetter interface {
	BaseURL() string
	Timeout() string
	EnableLogging() bool
	DefaultHeaders() map[string]string
	Retry() RetryConfig
}

// RestConfSetter is write-only interface for RestConf type
type RestConfSetter interface {
	SetBaseURL(string)
	SetTimeout(string)
	SetEnableLogging(bool)
	SetDefaultHeaders(map[string]string)
	SetRetry(RetryConfig)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (r RestConf) ShootNew() { /*noop*/ }
