// Code generated by "shoot rest -type=Client"; DO NOT EDIT. (v0.9.0-beta.4)

package client2

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"restclientexample/client2/dto"
	"strings"
	"time"

	"github.com/loopopen/shoot"
)

type client struct {
	client         *http.Client
	conf           *shoot.RestConf
	defaultTimeout time.Duration
}

func (_c *client) UpdateUser1(ctx context.Context, id int, user User) (*shoot.Response, error) {
	path_ := "/users/{id}"
	path_ = strings.Replace(path_, "{id}", url.PathEscape(fmt.Sprint(id)), 1)

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	bodyJson_, err := json.Marshal(user)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "PUT", url_, bytes.NewReader(bodyJson_))
	if err != nil {
		return nil, err
	}

	req_.Header.Set("Accept", "application/json")
	req_.Header.Set("Content-Type", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	call_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)
	if err != nil {
		return nil, err
	}
	defer call_.Cancel()

	resp_, err := shoot.Do(_c.client, req_, _c.conf.Retry(), call_)
	if err != nil {
		return nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	response_ := shoot.NewResponse(resp_, responseBody_)
	if err != nil {
		return response_, err
	}
	if closeErr_ != nil {
		return response_, closeErr_
	}

	return response_, nil
}

func (_c *client) UpdateUser2(ctx context.Context, id int, user dto.User) (*shoot.Response, error) {
	path_ := "/users/{id}"
	path_ = strings.Replace(path_, "{id}", url.PathEscape(fmt.Sprint(id)), 1)

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	bodyJson_, err := json.Marshal(user)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "PUT", url_, bytes.NewReader(bodyJson_))
	if err != nil {
		return nil, err
	}

	req_.Header.Set("Accept", "application/json")
	req_.Header.Set("Content-Type", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	call_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)
	if err != nil {
		return nil, err
	}
	defer call_.Cancel()

	resp_, err := shoot.Do(_c.client, req_, _c.conf.Retry(), call_)
	if err != nil {
		return nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	response_ := shoot.NewResponse(resp_, responseBody_)
	if err != nil {
		return response_, err
	}
	if closeErr_ != nil {
		return response_, closeErr_
	}

	return response_, nil
}

func (_c *client) PostNoBody() (*shoot.Response, error) {
	path_ := "/ping"

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequest("POST", url_, nil)
	if err != nil {
		return nil, err
	}

	req_.Header.Set("Accept", "application/json")
	req_.Header.Set("Content-Type", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	call_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)
	if err != nil {
		return nil, err
	}
	defer call_.Cancel()

	resp_, err := shoot.Do(_c.client, req_, _c.conf.Retry(), call_)
	if err != nil {
		return nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	response_ := shoot.NewResponse(resp_, responseBody_)
	if err != nil {
		return response_, err
	}
	if closeErr_ != nil {
		return response_, closeErr_
	}

	return response_, nil
}

func (_c *client) SetEnabled(ctx context.Context, enabled bool) (*shoot.Response, error) {
	path_ := "/enabled"

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	bodyJson_, err := json.Marshal(enabled)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "POST", url_, bytes.NewReader(bodyJson_))
	if err != nil {
		return nil, err
	}

	req_.Header.Set("Accept", "application/json")
	req_.Header.Set("Content-Type", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	call_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)
	if err != nil {
		return nil, err
	}
	defer call_.Cancel()

	resp_, err := shoot.Do(_c.client, req_, _c.conf.Retry(), call_)
	if err != nil {
		return nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	response_ := shoot.NewResponse(resp_, responseBody_)
	if err != nil {
		return response_, err
	}
	if closeErr_ != nil {
		return response_, closeErr_
	}

	return response_, nil
}

func (_c *client) ReplaceLabels(ctx context.Context, id int, labels map[string]string) (*shoot.Response, error) {
	path_ := "/users/{id}/labels"
	path_ = strings.Replace(path_, "{id}", url.PathEscape(fmt.Sprint(id)), 1)

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	bodyJson_, err := json.Marshal(labels)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "PATCH", url_, bytes.NewReader(bodyJson_))
	if err != nil {
		return nil, err
	}

	req_.Header.Set("Accept", "application/json")
	req_.Header.Set("Content-Type", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	call_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)
	if err != nil {
		return nil, err
	}
	defer call_.Cancel()

	resp_, err := shoot.Do(_c.client, req_, _c.conf.Retry(), call_)
	if err != nil {
		return nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	response_ := shoot.NewResponse(resp_, responseBody_)
	if err != nil {
		return response_, err
	}
	if closeErr_ != nil {
		return response_, closeErr_
	}

	return response_, nil
}

// ConfigHTTPClient allows customization of the underlying http.Client.
func (_c *client) ConfigHTTPClient(config func(*http.Client)) Client {
	config(_c.client)
	return _c
}

// ShootRest exists solely to fulfill the RestShooter interface contract.
func (_c *client) ShootRest() { /*noop*/ }

func init() {
	shoot.Register(func(conf shoot.RestConf) Client {
		timeout, err := time.ParseDuration(conf.Timeout())
		if err != nil {
			panic(err)
		}
		return &client{
			conf:           &conf,
			defaultTimeout: timeout,
			client: &http.Client{
				Transport: conf.BuildMiddleware(),
			},
		}
	})
}
