// Code generated by "shoot rest -type=Client"; DO NOT EDIT. (v0.8.1)

package myclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"

	"github.com/loopopen/shoot"
)

type client struct {
	client *http.Client
	conf   *shoot.RestConf
}

func (_c *client) Get(ctx context.Context, key string) (*KV, *shoot.Response, error) {
	path_ := "/get"

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "GET", url_, nil)
	if err != nil {
		return nil, nil, err
	}

	query_ := req_.URL.Query()
	query_.Set("key", fmt.Sprintf("%v", key))
	req_.URL.RawQuery = query_.Encode()

	req_.Header.Add("Accept", "application/json")
	req_.Header.Add("Authorization", "Basic dXNlcm5hbWU6cGFzc3dvcmQ=")

	resp_, err := _c.client.Do(req_)
	if err != nil {
		return nil, nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	response_ := shoot.NewResponse(resp_, responseBody_)
	if err != nil {
		return nil, response_, err
	}
	if closeErr_ != nil {
		return nil, response_, closeErr_
	}

	if !response_.IsSuccess() {
		return nil, response_, nil
	}

	var r_ KV
	err = json.NewDecoder(bytes.NewReader(responseBody_)).Decode(&r_)
	if err == io.EOF {
		err = nil //ignore EOF errors caused by empty response body
	}
	if err != nil {
		return nil, response_, err
	}
	return &r_, response_, nil
}

func (_c *client) Set(ctx context.Context, kv *KV) (*shoot.Response, error) {
	path_ := "/set"

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	bodyJson_, err := json.Marshal(kv)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "POST", url_, bytes.NewReader(bodyJson_))
	if err != nil {
		return nil, err
	}

	req_.Header.Add("Accept", "application/json")
	req_.Header.Add("Authorization", "Basic dXNlcm5hbWU6cGFzc3dvcmQ=")
	req_.Header.Add("Content-Type", "application/json")

	resp_, err := _c.client.Do(req_)
	if err != nil {
		return nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	response_ := shoot.NewResponse(resp_, responseBody_)
	if err != nil {
		return response_, err
	}
	if closeErr_ != nil {
		return response_, closeErr_
	}

	return response_, nil
}

func (_c *client) Download(ctx context.Context) (*shoot.StreamResponse, error) {
	path_ := "/download"

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "GET", url_, nil)
	if err != nil {
		return nil, err
	}

	req_.Header.Add("Accept", "application/json")
	req_.Header.Add("Authorization", "Basic dXNlcm5hbWU6cGFzc3dvcmQ=")

	resp_, err := _c.client.Do(req_)
	if err != nil {
		return nil, err
	}
	response_ := shoot.NewStreamResponse(resp_)

	return response_, nil
}

// ConfigHTTPClient allows customization of the underlying http.Client.
func (_c *client) ConfigHTTPClient(config func(*http.Client)) Client {
	config(_c.client)
	return _c
}

// ShootRest exists solely to fulfill the RestShooter interface contract.
func (_c *client) ShootRest() { /*noop*/ }

func init() {
	shoot.Register(func(conf shoot.RestConf) Client {
		timeout, err := time.ParseDuration(conf.Timeout())
		if err != nil {
			panic(err)
		}
		return &client{
			conf: &conf,
			client: &http.Client{
				Timeout:   timeout,
				Transport: conf.BuildMiddleware(),
			},
		}
	})
}
