// Code generated by "shoot map -path=../dest -alias=model -type=Event"; DO NOT EDIT. (v0.9.0-beta.4)

package src

import (
	model "mapperexample4/dest"
	"time"
)

// ToModel converts receiver to type model.Event
func (e *Event) ToModel() *model.Event {
	if e == nil {
		return nil
	}
	event_ := new(model.Event)
	event_.Elapsed = time.Duration(e.Elapsed)
	return event_
}

// FromModel reads from type model.Event, then writes back to receiver and returns it
func (e *Event) FromModel(event_ *model.Event) *Event {
	if event_ == nil {
		return nil
	}
	if e == nil {
		e = new(Event)
	} else {
		*e = Event{}
	}
	e.Elapsed = int64(event_.Elapsed)
	return e
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (e Event) ShootMap() { /*noop*/ }
