// Code generated by "shoot map -path=../dest -type=Record"; DO NOT EDIT. (v0.9.0-beta.5)

package src

import "mapperexample4/dest"

// ToDest converts receiver to type dest.Record
func (r *Record) ToDest() *dest.Record {
	if r == nil {
		return nil
	}
	record_ := new(dest.Record)
	record_.Label = *r.Label.ToDest()
	return record_
}

// FromDest reads from type dest.Record, then writes back to receiver and returns it
func (r *Record) FromDest(record_ *dest.Record) *Record {
	if record_ == nil {
		return nil
	}
	if r == nil {
		r = new(Record)
	} else {
		*r = Record{}
	}
	r.Label = *new(Label).FromDest(&record_.Label)
	return r
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (r Record) ShootMap() { /*noop*/ }
