// Code generated by "shoot enum -json -text -file=enums.go"; DO NOT EDIT. (v0.9.0-beta.3)

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/loopopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[LightRed-0]
	_ = x[LightYello-1]
	_ = x[LightGreen-2]
}

const _light_max = LightRed | LightYello | LightGreen

var _light_values = []Light{LightRed, LightYello, LightGreen}

var _light_strings = []string{"Red", "Yello", "Green"}

var _light_string_map = map[Light]string{
	LightRed:   "Red",
	LightYello: "Yello",
	LightGreen: "Green",
}

var _light_value_map = map[string]Light{
	"Red":   LightRed,
	"Yello": LightYello,
	"Green": LightGreen,
}

// String returns the string value of type Light
func (l Light) String() string {
	str, ok := _light_string_map[l]
	if ok {
		return str
	}
	if l < 0 || l > _light_max {
		return fmt.Sprintf("%d", l)
	}

	return fmt.Sprintf("%d", l)
}

func (l Light) Values() []Light {
	return _light_values
}

func (l Light) Strings() []string {
	return _light_strings
}

func (l Light) IsValid() bool {
	_, ok := _light_string_map[l]
	return ok
}

func (l Light) ValueMap() map[string]Light {
	return _light_value_map
}

func (l Light) StringMap() map[Light]string {
	return _light_string_map
}

// MarshalJSON implements the json.Marshaler interface for Light
func (l Light) MarshalJSON() ([]byte, error) {
	return json.Marshal(l.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Light
func (l *Light) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ Light
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("Light enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[Light](s_); err != nil {
		return err
	}
	*l = v_
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Light
func (l Light) MarshalText() ([]byte, error) {
	return []byte(l.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Light
func (l *Light) UnmarshalText(text []byte) error {
	var v_ Light
	var err error
	if v_, err = shoot.ParseEnum[Light](string(text)); err != nil {
		return err
	}
	*l = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (l Light) ShootEnum() { /*noop*/ }

func _() {
	var x [1]struct{}
	_ = x[StatusFailed-(-1)]
	_ = x[StatusPending-1]
	_ = x[StatusProcessing-2]
	_ = x[StatusSucceeded-3]
}

const _status_max = StatusFailed | StatusPending | StatusProcessing | StatusSucceeded

var _status_values = []Status{StatusFailed, StatusPending, StatusProcessing, StatusSucceeded}

var _status_strings = []string{"Failed", "Pending", "Processing", "Succeeded"}

var _status_string_map = map[Status]string{
	StatusFailed:     "Failed",
	StatusPending:    "Pending",
	StatusProcessing: "Processing",
	StatusSucceeded:  "Succeeded",
}

var _status_value_map = map[string]Status{
	"Failed":     StatusFailed,
	"Pending":    StatusPending,
	"Processing": StatusProcessing,
	"Succeeded":  StatusSucceeded,
}

// String returns the string value of type Status
func (s Status) String() string {
	str, ok := _status_string_map[s]
	if ok {
		return str
	}
	if s < 0 || s > _status_max {
		return fmt.Sprintf("%d", s)
	}

	return fmt.Sprintf("%d", s)
}

func (s Status) Values() []Status {
	return _status_values
}

func (s Status) Strings() []string {
	return _status_strings
}

func (s Status) IsValid() bool {
	_, ok := _status_string_map[s]
	return ok
}

func (s Status) ValueMap() map[string]Status {
	return _status_value_map
}

func (s Status) StringMap() map[Status]string {
	return _status_string_map
}

// MarshalJSON implements the json.Marshaler interface for Status
func (s Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Status
func (s *Status) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ Status
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("Status enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[Status](s_); err != nil {
		return err
	}
	*s = v_
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Status
func (s Status) MarshalText() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Status
func (s *Status) UnmarshalText(text []byte) error {
	var v_ Status
	var err error
	if v_, err = shoot.ParseEnum[Status](string(text)); err != nil {
		return err
	}
	*s = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (s Status) ShootEnum() { /*noop*/ }

func _() {
	var x [1]struct{}
	_ = x[OutOfOrderX-(-1)]
	_ = x[OutOfOrderA-1]
	_ = x[OutOfOrderB-2]
	_ = x[OutOfOrderC-3]
}

const _outOfOrder_max = OutOfOrderX | OutOfOrderA | OutOfOrderB | OutOfOrderC

var _outOfOrder_values = []OutOfOrder{OutOfOrderX, OutOfOrderA, OutOfOrderB, OutOfOrderC}

var _outOfOrder_strings = []string{"X", "A", "B", "C"}

var _outOfOrder_string_map = map[OutOfOrder]string{
	OutOfOrderX: "X",
	OutOfOrderA: "A",
	OutOfOrderB: "B",
	OutOfOrderC: "C",
}

var _outOfOrder_value_map = map[string]OutOfOrder{
	"X": OutOfOrderX,
	"A": OutOfOrderA,
	"B": OutOfOrderB,
	"C": OutOfOrderC,
}

// String returns the string value of type OutOfOrder
func (o OutOfOrder) String() string {
	str, ok := _outOfOrder_string_map[o]
	if ok {
		return str
	}
	if o < 0 || o > _outOfOrder_max {
		return fmt.Sprintf("%d", o)
	}

	return fmt.Sprintf("%d", o)
}

func (o OutOfOrder) Values() []OutOfOrder {
	return _outOfOrder_values
}

func (o OutOfOrder) Strings() []string {
	return _outOfOrder_strings
}

func (o OutOfOrder) IsValid() bool {
	_, ok := _outOfOrder_string_map[o]
	return ok
}

func (o OutOfOrder) ValueMap() map[string]OutOfOrder {
	return _outOfOrder_value_map
}

func (o OutOfOrder) StringMap() map[OutOfOrder]string {
	return _outOfOrder_string_map
}

// MarshalJSON implements the json.Marshaler interface for OutOfOrder
func (o OutOfOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OutOfOrder
func (o *OutOfOrder) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ OutOfOrder
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("OutOfOrder enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[OutOfOrder](s_); err != nil {
		return err
	}
	*o = v_
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for OutOfOrder
func (o OutOfOrder) MarshalText() ([]byte, error) {
	return []byte(o.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OutOfOrder
func (o *OutOfOrder) UnmarshalText(text []byte) error {
	var v_ OutOfOrder
	var err error
	if v_, err = shoot.ParseEnum[OutOfOrder](string(text)); err != nil {
		return err
	}
	*o = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (o OutOfOrder) ShootEnum() { /*noop*/ }
