// Code generated by "shoot enum -sql -file=status.go"; DO NOT EDIT. (v0.9.0-beta.5)

package status

import (
	"database/sql/driver"
	"errors"
	"fmt"

	"github.com/loopopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[StatusPending-0]
	_ = x[StatusPaid-1]
}

const _status_max = StatusPending | StatusPaid

var _status_values = []Status{StatusPending, StatusPaid}

var _status_strings = []string{"Pending", "Paid"}

var _status_string_map = map[Status]string{
	StatusPending: "Pending",
	StatusPaid:    "Paid",
}

var _status_value_map = map[string]Status{
	"Pending": StatusPending,
	"Paid":    StatusPaid,
}

// String returns the string value of type Status
func (s Status) String() string {
	str, ok := _status_string_map[s]
	if ok {
		return str
	}
	if s < 0 || s > _status_max {
		return fmt.Sprintf("%d", s)
	}

	return fmt.Sprintf("%d", s)
}

func (s Status) Values() []Status {
	return _status_values
}

func (s Status) Strings() []string {
	return _status_strings
}

func (s Status) IsValid() bool {
	_, ok := _status_string_map[s]
	return ok
}

func (s Status) ValueMap() map[string]Status {
	return _status_value_map
}

func (s Status) StringMap() map[Status]string {
	return _status_string_map
}

// Value implements the driver.Valuer interface for Status
func (s Status) Value() (driver.Value, error) {
	return s.String(), nil
}

// Scan implements the driver.Scanner interface for Status
func (s *Status) Scan(value interface{}) error {
	if value == nil {
		*s = 0
		return nil
	}
	var s_ string
	switch v_ := value.(type) {
	case []byte:
		s_ = string(v_)
	case string:
		s_ = v_
	default:
		return errors.New("bad enum type")
	}
	e_, err := shoot.ParseEnum[Status](s_)
	if err != nil {
		return err
	}
	*s = e_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (s Status) ShootEnum() { /*noop*/ }
